version: '3.8'

services:
  frontend-dev:
    build:
      context: ./cepv-frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./cepv-frontend:/app

  backend-dev:
    build:
      context: ./cepv-backend
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    environment:
      - 'REDIS_HOST=redis-dev'
    # restart: always
    
  redis-dev:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  
  reverse_proxy-dev:
    build:
      context: ./reverse_proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend-dev
      - frontend-dev
    # restart: always
    environment:
      - FRONTEND_ENDPOINT=frontend-dev:3000
      - BACKEND_ENDPOINT=backend-dev:5000