# syntax=docker/dockerfile:1
FROM python:3.10-slim-buster

# Necessary because apt does not install a sufficiently up to date version of cmake
RUN apt-get update \
  && apt-get -y install build-essential \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/* \
  && wget https://github.com/Kitware/CMake/releases/download/v3.24.1/cmake-3.24.1-Linux-x86_64.sh \
      -q -O /tmp/cmake-install.sh \
      && chmod u+x /tmp/cmake-install.sh \
      && mkdir /opt/cmake-3.24.1 \
      && /tmp/cmake-install.sh --skip-license --prefix=/opt/cmake-3.24.1 \
      && rm /tmp/cmake-install.sh \
      && ln -s /opt/cmake-3.24.1/bin/* /usr/local/bin

RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    gcc \
    xrootd* \
    zlib1g-dev \
    uuid-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    curl -y

RUN apt-get upgrade -y

WORKDIR /app

COPY requirements.txt /app
RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 5000

ENV FLASK_APP=flaskr

CMD ["flask", "run", "--host", "0.0.0.0"]